### ISSUE TITLE
Truncating Layer Names

### ISSUE THREAD

**Issue by MamaMightyMac** [chriswetterman/sketch-find-and-replace-text#10]
Hi, this plugin is just what I was looking for except my layer names are quite long (created from another plugin that generates artboard titles) I needed to strip out internal naming conventions prepended to the titles before sharing with the client.  Only your plug in keeps chopping off the end of the layer names.  The text portion works great! It did exactly what I needed.  Can you please look into it? Thanks.

**Comment by chriswetterman** [comment]
I have a future update that will allow renaming of layers, but currently that functionality doesn't exist. You are referencing layer names, not text objects, correct? Could you please provide some more details. Screenshots are welcome.

**Comment by chriswetterman** [comment]
Closing in lieu of #13. If you still have issues after updating please open another issue.
