### ISSUE TITLE
No plugin found in zip file

### ISSUE THREAD

**Issue by JefferyReidKnowde** [chriswetterman/sketch-find-and-replace-text#16]
Not finding the plugin in the ZIP file

**Comment by chriswetterman** [comment]
I just downloaded and tested it myself and the zip contained the plugin. Here is the link from the installation section. Let me know if you continue to have issues.

https://github.com/chriswetterman/sketch-find-and-replace-text/releases/latest/download/find-and-replace-text.sketchplugin.zip

**Comment by JefferyReidKnowde** [comment]
Thanks!


Jeffery Reid | CPO | Knowde.com | Mobile: 206-612-7009 

https://calendly.com/jefferyreid

**Comment by JefferyReidKnowde** [comment]
I went back to see the issue and it’s with the Github version, not the version you download from your site

Here’s a vid showing it

https://www.dropbox.com/s/zhet52icqxzfobz/find%20and%20replace.mp4?dl=0 <https://www.dropbox.com/s/zhet52icqxzfobz/find%20and%20replace.mp4?dl=0>

All the best

Jeff


Jeffery Reid | CPO | Knowde.com | Mobile: 206-612-7009 

https://calendly.com/jefferyreid

**Comment by chriswetterman** [comment]
Correct. You had downloaded the raw source, not the built release of the extension.
