### ISSUE TITLE
"Find Next" doesn't seem to center the selection or target the correct artboard

### ISSUE THREAD

**Issue by cawenzel** [chriswetterman/sketch-find-and-replace-text#4]
Thanks again Chris for the update. The plugin is now showing for me. I have run into a new bug in which, once I run the query to search either the "Document", "Page", etc, that it doesn't seem to center the selection properly (even though the canvas moves based on the active selection). Please feel free to let me know if you need any additional details.

**Comment by chriswetterman** [comment]
Chris,

Thanks for pointing this out. I have seen it happen, but not consistently, and will take a further look into this.

**Comment by chriswetterman** [comment]
#8 was created to follow a Sketch API bug affecting centering
